# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello_world <- function() {
    .Call(`_mashproto_rcpp_hello_world`)
}

movement_init <- function(parameters) {
    .Call(`_mashproto_movement_init`, parameters)
}

movement_step <- function(module, time_step) {
    .Call(`_mashproto_movement_step`, module, time_step)
}

convert_to_r_movement <- function(movement_list, human) {
    invisible(.Call(`_mashproto_convert_to_r_movement`, movement_list, human))
}

movements_of_human <- function(movement_list, human) {
    .Call(`_mashproto_movements_of_human`, movement_list, human)
}

